# @package _global_

module:
  _target_: emg2qwerty.lightning.CNNRNNCTCModule
  in_features: 528
  mlp_features: [384]

  conv_channels: 256 #256
  conv_kernel_size: 7 #5
  conv_num_layers: 2 #2
  conv_dropout: 0.2

  rnn_hidden_size: 512
  rnn_num_layers: 3
  rnn_dropout: 0.45
  bidirectional: true
  rnn_type: gru

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]